version: '3.8'

services:

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge